### ISSUE TITLE
invalid control type error when clicking view button under 项目申请列表 page

### ISSUE THREAD

**Issue by shuyutang** [yannonghuang/shinshin#10]
在“项目申请列表”页面下， 点击任意一个项目的“查看”按钮，跳转界面会显示“invalid control type"，虽然页面内容还是可以正常显示。
![image](https://user-images.githubusercontent.com/25158008/159189325-814ee1c6-d47e-4723-a496-4048378d91f9.png)

**Comment by yannonghuang** [comment]
apparently, db instance was not properly loaded, needs to be rebuilt

**Comment by jianhe7** [comment]
Please export mysql database nodedb to one .sql file (mysqldump -u root -p nodedb > backup_nodedb.sql), and send it to me. Last time, I had to import the folder of .sql files to my local machine, then export all to one .sql file, before importing the single file using mysql command line on the server. Some format may be messed up? Also 
Mysql shows error:Unknown collation: utf8mb4_0900_ai_ci (The collation id may difference based on MySQL version.)
So, I had to use the following to convert the format
sed -i 's/utf8mb4_0900_ai_ci/utf8_general_ci/g' dumpxxx.sql  
            sed -i 's/CHARSET=utf8mb4/CHARSET=utf8/g' dumpxxx.sql 
Then, import the data
            mysql -u root -p nodedb < dumpxxx.sql

**Comment by jianhe7** [comment]
This looks like a formbuilder registering issue. Maybe, the old forms imported from the old spm need to be registered to the react formBuilder?

**Comment by yannonghuang** [comment]
make sure to use the right version (see package.json):

    "formBuilder": "^3.7.3",
    "jquery": "^3.6.0",

**Comment by yannonghuang** [comment]
This is related to the fact that Mysql and MarisDB handle json columns in different ways. A new check-in fixes this issue. But it is suggested to use Mysql if possible.

**Comment by jianhe7** [comment]
Re-installed MySQL 8.0 to replace MariaDB, and this problem is gone. Attach two npm audit reports that show vulnerability issues. 
[npm_audit_react-app.txt](https://github.com/yannonghuang/shinshin/files/8394419/npm_audit_react-app.txt)
[npm_audit_backend.txt](https://github.com/yannonghuang/shinshin/files/8394420/npm_audit_backend.txt)
