### ISSUE TITLE
用户列表下查询需要 添加用电邮查询账号

### ISSUE THREAD

**Issue by jianhe7** [yannonghuang/shinshin#13]
以前有老师发电邮问起账号问题， 经常没有姓名信息，我只好用电邮地址查询。而且，发现很多老账号用的同一电邮地址，应该清理只允许一个电邮对应一个账号。

**Comment by yannonghuang** [comment]
是的，一个电邮对应一个账号

**Comment by yannonghuang** [comment]
fixed

**Comment by jianhe7** [comment]
It doesn't show the results, after I click on the "Search" button with any email address.

**Comment by jianhe7** [comment]
I stopped apache sever, and open 8080 port by adding a rule to aws console. Now it runs node server only, but still the search button doesn't work for email address. 

You can access it at http://44.241.159.131:8080/

<img width="574" alt="Screen Shot 2022-03-29 at 10 40 33 PM" src="https://user-images.githubusercontent.com/11562782/160759364-2e19b492-c5d6-4863-bb85-a95569fbfa4e.png">
<img width="697" alt="Screen Shot 2022-03-29 at 10 39 57 PM" src="https://user-images.githubusercontent.com/11562782/160759376-27431600-d3f7-4760-878f-baf15b7aa750.png">

**Comment by jianhe7** [comment]
After upgrading the node to 16., this issue is gone.
