### ISSUE TITLE
学校用户类型为何有“欣欣义工”？

### ISSUE THREAD

**Issue by jianhe7** [yannonghuang/shinshin#5]
老系统里欣欣义工是管理员内部创建， 因为欣欣必须面试并确认义工之后，发给IT义工创建账号。
<img width="964" alt="Screen Shot 2022-03-16 at 5 39 25 PM" src="https://user-images.githubusercontent.com/11562782/158714049-7a7c7ba1-b836-4811-b557-82e95effd139.png">

**Comment by yannonghuang** [comment]
removed "欣欣义工“ from the dropdown list.
