### ISSUE TITLE
为何重庆市五个学校不在列表里？

### ISSUE THREAD

**Issue by jianhe7** [yannonghuang/shinshin#67]
<img width="480" alt="Screen Shot 2022-06-20 at 10 41 39 PM" src="https://user-images.githubusercontent.com/11562782/174724557-cdd283a6-26c6-4466-95d9-c31c503f8ba7.png">

old SPM：
<img width="449" alt="Screen Shot 2022-06-20 at 10 42 40 PM" src="https://user-images.githubusercontent.com/11562782/174724699-a68bf679-2012-49cf-abb4-c7d0ad8f9b09.png">

**Comment by jianhe7** [comment]
广西10所也不在列表：
<img width="327" alt="Screen Shot 2022-06-20 at 10 45 11 PM" src="https://user-images.githubusercontent.com/11562782/174725071-c42b9d7a-4801-4471-85fc-23ccd9ee8866.png">

**Comment by jianhe7** [comment]
内蒙古6所也没有

**Comment by jianhe7** [comment]
新疆6所， 宁夏11所 也是查看没有。数据库查看有问题。

**Comment by yannonghuang** [comment]
[Dump20220620.sql.zip](https://github.com/yannonghuang/shinshin/files/8946475/Dump20220620.sql.zip)

pls import the dump then "git pull"
