### ISSUE TITLE
“导出” “详细导出”按钮没有反应

### ISSUE THREAD

**Issue by shuyutang** [yannonghuang/shinshin#8]
在学校列表界面，点击“导出”、“详细导出”按钮都没有反应

**Comment by yannonghuang** [comment]
depending the browser, for example, with Chrome, exported files will be saved automatically in the "download" folder

**Comment by yannonghuang** [comment]
make sure to be logged in in order to export

**Comment by jianhe7** [comment]
If exporting buttons are only working for users who logged in, please hide them when users are not logged in. Or pop up a message they need to login first before exporting.

**Comment by yannonghuang** [comment]
good suggestion, fixed, thx

**Comment by yannonghuang** [comment]
Tested with MariaDB 10.6 & Mysql 8.x, worked fine.

Suggested either to use Mysql or upgrade MariaDB.

**Comment by jianhe7** [comment]
With MySQL 8.0, and Node 16.14.2, but I still can't see any actions after clicking on the button "Export" with or without Apache running (I stopped it then, use http://44.241.159.131:8080/ to test, still doesn't do any work for "Export" and "Full Export").

**Comment by yannonghuang** [comment]
pls refresh the codebase, I added a few debugging messages to probe whats going on ...

**Comment by jianhe7** [comment]
Attach the output.log
[output.log](https://github.com/yannonghuang/shinshin/files/8394946/output.log)

**Comment by yannonghuang** [comment]
fixed

**Comment by jianhe7** [comment]
Tested both buttons and they work now. @shuyutang you may test this again. If it works, please close this issue. Thanks!
